[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "npm ci --legacy-peer-deps",
  "cd apps/shared && npm install && npm run build",
  "cd apps/backend && npm install --legacy-peer-deps"
]

[phases.build]
cmds = ["cd apps/backend && npm run build"]

[start]
cmd = "cd apps/backend && npm start"
