[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install --prefix apps/shared",
  "npm run build --prefix apps/shared",
  "npm install --prefix apps/backend --legacy-peer-deps"
]

[phases.build]
cmds = ["npm run build --prefix apps/backend"]

[start]
cmd = "node apps/backend/dist/server.js"
